// Generated by https://quicktype.io

export interface Documents {
    documentos: Documento[];
}

export interface Documento {
    id:         number;
    name:       string;
    code:       string;
    created_at: null;
    updated_at: null;
}
